# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # 加载 ec_sys 开启写权限
  boot.kernelModules = [ "kvm-intel" "ec_sys" ];
  boot.extraModprobeConfig = ''
    options ec_sys write_support=1
  '';
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      # noatime：SSD 上 atime 更新纯属写放大；ssd 选项对 NVMe 由内核自动启用，无需显式指定
      options = [ "subvol=@" "noatime" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      options = [ "subvol=@var" "noatime" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" ];
    };

  fileSystems."/var/lib/docker" =
    {
      device = "/dev/disk/by-uuid/e0d906dd-b7af-4537-95c2-24595906fbce";
      fsType = "btrfs";
      options = [ "subvol=@docker" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1C91-1740";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/6af40d3c-fdfa-42fc-ad9c-7c57966be306"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
