# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/251f2194-cfde-4826-afcb-a7b117c9d4dd";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/41E5-09F9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3ab23e06-e327-4a55-80e3-1a85e0901274"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
