# Playback
# 播放结束后保持窗口
keep-open=yes
# 播放结束后显示最后一帧
keep-open-pause=yes


# Hardware acceleration
# 使用 GPU 渲染
vo=gpu-next
# Vulkan 后端
gpu-api=vulkan
# NVIDIA 硬件解码
hwdec=nvdec


# Video quality
# 高质量缩放
scale=ewa_lanczos
cscale=ewa_lanczos


# Sync
# 适合笔记本屏幕
video-sync=display-resample


# UI
# 启动时默认不显示 OSC
osc=no
# 默认音量
volume=70


# Screenshot
screenshot-format=png
screenshot-directory=~/Pictures/mpv

# Custom uosc titlebar
border=no

# Use custom feedback; hide mpv built-in status text and progress bars.
osd-level=0
osd-bar=no
