name: "Publish every Git push to main to FlakeHub"
on:
  workflow_run:
    workflows: ["CI: build check all hosts"]
    branches: [main]
    types: [completed]
jobs:
  flakehub-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "wmjim/nixos-config"
          rolling: true
          visibility: "public"
          include-output-paths: true
